spring:
  rabbitmq:
    host: 124.221.70.206
    port: 5672
    virtual-host: /
    username: root
    password: 123456
    listener:
      simple:
        prefetch: 1   # Pre-allocate 1 person who can do more work